### ISSUE TITLE
Matrix client as VoIP softphone replacement

### ISSUE THREAD

**Issue by tompinzler** [kamax-io/matrix-appservice-voip#1]
I'm thrilled to see Matrix <-> VoIP integration.

As far as I understand the current integration allows to make VoIP calls to other Matrix users.

I wonder if you plan to make and receive calls to and from normal phone numbers. I'm interested to add functionality to the Matrix client that allows us to replace VoIP softphones like Bria or Zoiper.

My colleague and I don't have Java development skills yet but want to help going in that direction.

**Comment by maxidorius** [comment]
Thank you for your interest! It's great to see others are just as thrilled as we are about VoIP.

This bridge is especially targeted to the regular phone network (PSTN) and is already fully capable of supporting it using FreeSWITCH + SIP provider for both making and receiving calls, and was the point of the v0.1.0 release.

We are due to release a guide to setup FreeSWITCH correctly so it works as expected for those unfamiliar with FreeSWITCH setup & config, as we have found out ourselves that it is not straightforward.

So yes, what triggered this bridge is to definitely use a Matrix/[The Grid](https://github.com/thegridprotocol/thegrid) client as a softphone replacement.

We have further plans to also:
- Create some kind of dedicated client targeted to nicely integrate with this bridge, so the user experience is much improved.
- Integrate with SIP directly (still need to validate if feasible without a MCU due to codecs differences)
- Integrate with another bridge to a network where VoIP also exists, like Discord, and thus create some kind of double integration. We don't know yet if actually feasible, but we'll try.

If you would like to help, I recommend joining [the dedicated Matrix room](https://matrix.to/#/#matrix-appservice-voip:kamax.io) so we can discuss it, or directly contact me at [@max:kamax.io](https://matrix.to/#/@max:kamax.io)

**Comment by tompinzler** [comment]
Very nice! Sounds like we are going in the same direction as you do and should definitely join forces.

I will start playing with your bridge as soon as the guide is available and  join you in the Matrix room afterwards.

Will close the ticket now.
